# Generated by Django 2.2.5 on 2019-09-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_user_pay_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_value', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor Pago')),
                ('value_to_be_paid', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor a ser Pago')),
                ('payment_date', models.DateField(auto_now=True, verbose_name='Data da efetuação do pagamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_payments', to='user.User')),
            ],
            options={
                'verbose_name': 'Registro Pagamento',
                'verbose_name_plural': 'Registros de Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=30, verbose_name='Valor da dívida')),
                ('debtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
