# Generated by Django 2.2.5 on 2019-09-25 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'verbose_name': 'Dívida', 'verbose_name_plural': 'Dívidas'},
        ),
        migrations.AddField(
            model_name='debt',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.PaymentRegister'),
            preserve_default=False,
        ),
    ]
