# Generated by Django 2.2.5 on 2019-10-01 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190925_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data do débito'),
        ),
    ]
