# Generated by Django 2.2.5 on 2019-10-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_debt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentregister',
            name='payment_date',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data da efetuação do pagamento'),
        ),
    ]
