# Generated by Django 2.2.5 on 2019-09-24 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190924_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pay_day',
            field=models.IntegerField(default=1, verbose_name='Dia do mês que é realizado o Pagamento'),
            preserve_default=False,
        ),
    ]
