# Generated by Django 2.2.5 on 2019-09-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_pay_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Nome da Banca'),
        ),
    ]
