# Generated by Django 2.2.5 on 2019-10-01 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_store_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_subscription',
            field=models.DateField(default=datetime.datetime.today, verbose_name='Data de entrada no sistema'),
        ),
    ]
